# Generated by Django 5.0.2 on 2024-03-05 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipes', '0002_ingredientslist_ingredientsrecipe_and_more'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fridge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.user')),
            ],
        ),
        migrations.CreateModel(
            name='FridgeIngredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_fridge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fridge.fridge')),
                ('id_ingredients_list', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='recipes.ingredientslist')),
            ],
        ),
    ]
