# Generated by Django 5.0.2 on 2024-03-27 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fridge', '0001_initial'),
        ('recipes', '0019_remove_ingredientslist_recipe_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fridgeingredients',
            name='id_ingredients_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='recipes.ingredients'),
        ),
    ]
