# Generated by Django 5.0.2 on 2024-03-27 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fridge', '0002_alter_fridgeingredients_id_ingredients_list'),
        ('recipes', '0021_ingredient_remove_ingredients_recipe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fridgeingredients',
            name='id_ingredients_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='recipes.ingredient'),
        ),
    ]
