# Generated by Django 5.0.2 on 2024-04-01 13:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fridge', '0003_alter_fridgeingredients_id_ingredients_list'),
        ('recipes', '0023_alter_recipemodel_ingredients'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fridgeingredients',
            name='id_fridge',
        ),
        migrations.RemoveField(
            model_name='fridgeingredients',
            name='id_ingredients_list',
        ),
        migrations.CreateModel(
            name='FridgeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='recipes.ingredient')),
            ],
        ),
        migrations.DeleteModel(
            name='Fridge',
        ),
        migrations.DeleteModel(
            name='FridgeIngredients',
        ),
    ]
