# Generated by Django 5.0.2 on 2024-04-01 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fridge', '0004_remove_fridgeingredients_id_fridge_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fridgeingredient',
            old_name='ingredient',
            new_name='fridgeingredient',
        ),
    ]
