# Generated by Django 5.0.2 on 2024-04-01 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fridge', '0005_rename_ingredient_fridgeingredient_fridgeingredient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fridgeingredient',
            old_name='fridgeingredient',
            new_name='ingredient',
        ),
    ]
