# Generated by Django 5.0.2 on 2024-03-07 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_alter_ingredientslist_type_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipemodel',
            name='image',
            field=models.ImageField(null=True, upload_to='recipes/'),
        ),
    ]
