# Generated by Django 5.0.2 on 2024-03-07 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_recipemodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipemodel',
            name='time',
            field=models.IntegerField(null=True),
        ),
    ]
