# Generated by Django 5.0.2 on 2024-03-07 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_recipemodel_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipemodel',
            name='time',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
