# Generated by Django 5.0.2 on 2024-03-07 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_alter_recipemodel_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipemodel',
            name='time',
            field=models.IntegerField(null=True),
        ),
    ]
