# Generated by Django 5.0.2 on 2024-03-07 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_alter_recipemodel_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipemodel',
            name='steps',
            field=models.TextField(max_length=10000),
        ),
    ]
