# Generated by Django 5.0.2 on 2024-03-07 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0014_alter_recipemodel_steps'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipemodel',
            old_name='steps',
            new_name='step1',
        ),
        migrations.AddField(
            model_name='recipemodel',
            name='step2',
            field=models.TextField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='recipemodel',
            name='step3',
            field=models.TextField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='recipemodel',
            name='step4',
            field=models.TextField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='recipemodel',
            name='step5',
            field=models.TextField(max_length=10000, null=True),
        ),
    ]
