# Generated by Django 5.0.2 on 2024-03-07 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0015_rename_steps_recipemodel_step1_recipemodel_step2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipemodel',
            name='step1',
        ),
        migrations.RemoveField(
            model_name='recipemodel',
            name='step2',
        ),
        migrations.RemoveField(
            model_name='recipemodel',
            name='step3',
        ),
        migrations.RemoveField(
            model_name='recipemodel',
            name='step4',
        ),
        migrations.RemoveField(
            model_name='recipemodel',
            name='step5',
        ),
        migrations.CreateModel(
            name='RecipeSteps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_description', models.TextField()),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipemodel')),
            ],
        ),
    ]
