# Generated by Django 5.0.2 on 2024-03-11 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0016_remove_recipemodel_step1_remove_recipemodel_step2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipemodel',
            name='difficulty',
            field=models.CharField(choices=[('1', 'Easy'), ('2', 'Medium'), ('3', 'Experienced')], max_length=20, null=True),
        ),
    ]
