# Generated by Django 5.0.2 on 2024-03-26 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0017_recipemodel_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientslist',
            name='recipe',
            field=models.ManyToManyField(related_name='recipe_ingredients', to='recipes.recipemodel'),
        ),
        migrations.DeleteModel(
            name='IngredientsRecipe',
        ),
    ]
