# Generated by Django 5.0.2 on 2024-03-27 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fridge', '0003_alter_fridgeingredients_id_ingredients_list'),
        ('recipes', '0021_ingredient_remove_ingredients_recipe_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ingredients',
        ),
    ]
