# Generated by Django 5.0.2 on 2024-04-02 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0023_alter_recipemodel_ingredients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='type_quantity',
        ),
    ]
